### PR TITLE
Fixes issue #120 - PATCH request with body

### PR DESCRIPTION
**Pull request by marknuzz**
I did not have time to build this, as the dependencies were quite lengthy on my system to get albacore up and running, and I do not have fast internet right now. It seems to be simple enough. Can you verify that it works?

### CODE REVIEW

**Comment by haf** [comment]
Thank you. Please be aware that anything left untested is unsupported behaviour and may be removed at any point. It would be good if you send a unit test.

**Comment by HoraceGonzalez** [comment]
@haf, I will pull this down and verify. Will be happy to commit unit tests as well. Once this is in, is their anything preventing this fix from being rolled out to nuget as a minor release?

**Comment by haf** [comment]
No nothing is preventing release.

**Comment by HoraceGonzalez** [comment]
@haf, so after your morning coffee perhaps? :) I built locally, verified the fix, and sent a PR implementing the unit tests for this.

**Comment by haf** [comment]
Excellent; sure – after the morning coffee sounds like a plan.

**Comment by HoraceGonzalez** [comment]
Hi, @haf! Wanted to pester you about releasing this PR. What do you say? 

Much obliged.

**Comment by haf** [comment]
Done!

**Comment by HoraceGonzalez** [comment]
Internet magic. Amazing. Thank you!

**Pull request merged**
