### PR TITLE
Added support for NTLM requests

### PR DESCRIPTION
**Pull request by MattHartz**
Added new functions withNTLMAuthentication and setNetworkCredentials.

Changed ProxyCredentials to just Credentials.

### CODE REVIEW

**Comment by relentless** [comment]
This broke the AppVeyor (Windows) build - I'll try and have a look sometime this week, but if you get a chance first then go for it.

**Comment by MattHartz** [comment]
Yeah, I’ll take care of it.  Might be later towards the end of the week.

**Comment by relentless** [comment]
Oh, and thanks for the PR! :-)

**Comment by MattHartz** [comment]
Yeah, at quick glance, not sure what it is chewing on to fail at failwith.

**Comment by haf** [comment]
Closing due to lack of progress / dead PR. If you rebase and make the tests pass I can merge.

**Pull request closed without merging**
