### PR TITLE
Added HttpWebRequest.Timeout property to builder.

### PR DESCRIPTION
**Pull request by Muhomorik**
Not sure if it's useful to implement Timeout because it's such a [special thing](http://stackoverflow.com/questions/1500955/adjusting-httpwebrequest-connection-timeout-in-c-sharp) .
Tests are marked with categories for Visual Studio Test Explorer (shown as traits).

### CODE REVIEW

**Comment by relentless** [comment]
Hi Dmitri, yes I never realised there were these issues with timeouts.  Did you try testing it against something that was down?  Did the timeout work?

Assuming it generally works, yes definitely worth having.  Useful in general, and also we'll need it if @haf still wants to use it on Suave.

I haven't had a thorough look at the code yet, but in general it looks good.  It's good to see you added tests (not everyone does!), there's good info in the comment and it's good you've kept the timeout the same as the default.  Testing it against HttpWebRequest is an interesting idea (although I think we'd want to keep it the same even if the HttpWebRequest one changed).

I've seen a couple of things I wasn't sure about though:
- Can we make the integration tests automated instead of manual?
- In the integration tests, I'm not sure we're really testing the timeout as nothing is called which actually times out from what I can tell
- What do the 'UnitFluentBuilder' and 'MagicConstants' test categories represent?  I'm happy to have categories, but it would be good to keep them for things which differentiate the tests e.g. fast/slow, those with external dependencies, etc.
- There's already a unit tests which checks the defaults, named 'createRequest makes a Request with a Method and URL, and sensible defaults'.  We might want to add the timeout default to that instead of creating a separate one (just because having a separate one for all of the default will add lots of very small tests).  Admittedly, that test isn't named too well and should probably be split into one for the defaults and one for the other bits.
- I'm not sure we need Timeout as one of the the RequestHeader cases, as far as I can tell it isn't a standard HTTP header or needed to make timeouts work.
- Assuming we don't need a Timeout header, we can also remove it from the 'setHeaders' function
- I don't think the Timeout property on the Request record needs to be (or should be) mutable.  When we change it with 'withTimeout', we create a new record.  Keeping everything immutable is more idiomatic with F#, so I'm keeping everything immutable where possible.
- in the 'withTimeout' function, the second parameter should be 'request', as that's what we're updating.

If you have time to look at any of those that's cool, if not I'll merge it and take a look when I get the chance.

Thanks!

**Comment by haf** [comment]
Yes, want to use ;), but we're in a focus-mode right now. Will be back.

In long run, I think there should be a TCP stack in F# where you can handle all states explicitly, to go together with equivalent the HTTP state machine -- that would make bugs like this non-existent, because the state of a timeout would have to be handled somehow, or willfully ignored.

**Comment by Muhomorik** [comment]
@relentless 
- I don't want to wait 100s for an answer so, quite often 30s is more then enough.
- I can try to make a real test, although I need more digging in Nancy. I am not really sure how to do it. Probably set a low, 2s TO and put Nancy to sleep. 
  do! Async.Sleep 3000
- The original idea was to use an option (member). If TO is not set (None) then replace it with the default value from underlying class during request. Or simply have it as Int.

It looks like you are talking about something like that, right? 

Yes, I can make it.
- There is a todo on that test so I've decided not to change it.

**Comment by relentless** [comment]
Yes, just set a low timeout and sleep Nancy should do the trick.  You can add another endpoint in HttpServer.fs something like:

self.Get.["SlowResponse"] <- 
  fun _ -> 
    // sleep a bit
    200 :> obj

You probably don't even need to make the Timeout an option as it can always have a value, it will initially be set to the default.

I see what you mean about the todo - you can ignore that, but whether you update that test or not isn't important, I'll try and tidy the tests up a bit next time I'm in there.

Another thing that I forgot to mention, I was thinking it would be good to be specific about what unit the timout is using, perhaps by either:
- Calling it something like TimeoutMS instead of just Timeout
- Using units of measure, so it's something like withTimeout(300<ms>)

I don't know what would work best - you could try them out and see what you think, or just leave it as Timeout and I'll have a look myself.

**Comment by Muhomorik** [comment]
@relentless 
Okay, finally got some time to fix it.
Do you think his is better? I can make a new PR then.
https://github.com/Muhomorik/Http.fs/commit/a0af7f25f1825202b78af8f603b6445f9c8f87bd
If it is ok, I'll add ResponseUri later.

**Comment by relentless** [comment]
Hi @Muhomorik, sorry for not replying sooner, I've been busy trying to move house.  Yes, that looks great!  I'll close this PR, if you could make a new one.

In hindsight it might have been good to catch the WebExceptions and throw something else to isolate the user from WebRequest entirely, but that will have to wait until v2..

**Pull request closed without merging**
