### PR TITLE
Fix issue with double ? in query string

### PR DESCRIPTION
**Pull request by xkrt**
Hi, looks like I found a bug. Please, look at test and fix.
I checked this with Windows + .NET 4.6.1 and Linux + Mono 4.2.3.4, bug reproduces on both platforms.
Surprising that this bug was introduced so long ago:)

@relentless @haf please verify and publish new nuget version

### CODE REVIEW

**Comment by xkrt** [comment]
Without fix test fails with:

```
http web request url: Failed:
should equal
Expected: "http://localhost/?a=1"
Actual: "http://localhost/??a=1"
```

**Comment by haf** [comment]
@xkrt I haven't yet merged Http.fs-prerelease back to this repo due to lack of time. I can merge this to my fork and then merge back here later. PR to fork = release now.

**Comment by xkrt** [comment]
@haf I found https://github.com/haf/Http.fs/commit/e8157cc4155b7479bd93c7bf7e7165bb772c5b8b by @lapponiandevil, but fix not in https://github.com/haf/Http.fs/blob/master/HttpFs/Client.fs
Something goes wrong?

**Comment by haf** [comment]
I'll let Mikko have a look Monday. If that commit is not a parent of master@HEAD then it should be merged to master again.

PS: good catch! =)

**Comment by haf** [comment]
@xkrt Btw I can take your merge into the repo and release a version of Http.fs with it if you think it's good enough as-is?

**Comment by xkrt** [comment]
@haf yeah, that will be great

**Comment by xkrt** [comment]
@haf plz, do not forget nuget release

**Comment by xkrt** [comment]
@haf can you release nuget package of Http.fs-prerelease with https://github.com/haf/Http.fs/commit/e8157cc4155b7479bd93c7bf7e7165bb772c5b8b? I think -prerelease is only production-ready for now since it have `withTimeout`

**Comment by haf** [comment]
I tried releasing this PR but I don't have access to the main nuget /cc @relentless

**Comment by haf** [comment]
@xkrt Can you PR so that it's what you think will work on the master branch? I'm not able to write code right now. I'll release the prerelease nuget again then.

**Pull request merged**
