### PR TITLE
Feature/bodies

### LINKED ISSUE #65: [Body] Support the different sorts of bodies
### Description

As a part of making Http.fs a nice general-purpose Http client for .Net, we should support `multipart/form-data` bodies. They are needed to avoid the exploding size of application/x-www-form-urlencoded. They are needed to name file uploads and to upload files in general. By using them, we can set a MIME type for each body entity.
## Implementation

Suggesting that we implement a discriminated union for each of:
- multipart/form-data bodies
  - multipart/form-data -- **DONE**
  - multipart/mixed inside form-data -- **DONE**
  - plain encoding of files -- **DONE**
  - base64 encoding of files -- **DONE**
  - binary encoding of files -- this could be done when we have the 'socket' type, by composing it nicely **DONE**
- application/x-www-form-urlencoded -- **DONE**
- raw bytes
  - base64 encoded bytes
  - binary write-straight-to-stream bytes *_DONE_
- socket -- awaiting discussion

The raw-bytes body is well put to use for intermediate uploads, from 30MB to half a gig, depending on your machines' memory configuration.

The socket body can be used to stream data to the target web server, and if we choose to do #64, will fit well together with it. It would allow plugins like a websocket client, SSE client, webrtc client etc.

The form-data body type will contain randomized boundaries, so there should be a way to generate bodies deterministically.
### Handling data structure

We have these sorts of data; binary blob, streamed (both of which are easy and low on abstraction), form-data (key-value like), file-data (key-key-mime-base64 like). Both form-data and file-data can be formatted for `multipart/form-data` and `application/x-www-form-urlencoded` so I suggest a **typed model** for key-value and key-key-mime-base64 typed values, with can then be written using **formatters**. RawBytes bodies could be a specialisation of Socket (/cc @ademar - couldn't we do this for the new 'writePreamble' in Suave, too? Composing writers, one of which would be responsible for writing the preamble, into the SocketTask?).

Let's see what I can cook; right now I have a need for form-data and urlencoded, so I will focus on that.

### PR DESCRIPTION
**Pull request by haf**
A PR based on the previous two PRs, aiming to fix #65

### CODE REVIEW

**Comment by haf** [comment]
_this_ PR is the one I really care about ;). Or the stuff that starts from the first [requestbody] commit to be specific.

**Comment by haf** [comment]
Rebasing against master.

**Comment by relentless** [comment]
I'll just wait until you're done then.  Will this include the Fuchu changes as well?

**Comment by haf** [comment]
Yes

**Comment by haf** [comment]
New issue after rebase: https://github.com/relentless/Http.fs/issues/82

**Comment by haf** [comment]
Rebase done. Afk for a while now. You should be able to test this.

**Comment by relentless** [comment]
Not sure what's going on here, there seems to be some issue with the Fsharp.core reference in the unit tests, and the integration tests hang at some point.

**Comment by relentless** [comment]
The fsharp.core redirect in the unit test project needs updating to 4.3.1.  I'm getting two failures now, related to the multi-part file upload:

formatting different sorts of body/can format multipart/formdata single file: Failed:
should have correct body
Expected: "Content-Type: multipart/form-data; boundary=mACKqCcIID-J''_PL:hfbFiOLC/cew

--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="submit-name"

Larry
--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--mACKqCcIID-J''_PL:hfbFiOLC/cew--"
Actual: "Content-Type: multipart/form-data; boundary=nLWsTCFurKCiU_PjC/cCmmU-tnJHHa

--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="submit-name"

Larry
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa--"
  g:\prg\Fuchu\Fuchu\Assertions.fs(13,1): <StartupCode$Fuchu>.$Assertions.Equal@13.Invoke(String msg)
 (00:00:00.0334506)

formatting different sorts of body/can format multipart/formdata with multipart/mixed for multi-file upload: Failed:
should have correct body
Expected: "Content-Type: multipart/form-data; boundary=mACKqCcIID-J''_PL:hfbFiOLC/cew

--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="submit-name"

Larry
--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Type: multipart/mixed; boundary=iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: form-data; name="files"

--iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: file; filename="file1.txt"
Content-Type: text/plain

Hello World
--iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: file; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--iDnsCZhfTqMSYsj:LhBTftNfVog:eA--
--mACKqCcIID-J''_PL:hfbFiOLC/cew--"
Actual: "Content-Type: multipart/form-data; boundary=nLWsTCFurKCiU_PjC/cCmmU-tnJHHa

--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="submit-name"

Larry
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Type: multipart/mixed; boundary=BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: form-data; name="files"

--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: file; filename="file1.txt"
Content-Type: text/plain

Hello World
--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: file; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF--
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa--"
  g:\prg\Fuchu\Fuchu\Assertions.fs(13,1): <StartupCode$Fuchu>.$Assertions.Equal@13.Invoke(String msg)

**Comment by relentless** [comment]
Also, the integration tests hang on this:

****\* HttpClient_SuaveIntegrationTests+Suave Integration Tests.server receives valid filenames
get response body
[I] 2015-04-06T21:47:59.5908870Z: listener started in 97.069 ms with binding 127.0.0.1:8083 [Suave.Tcp.tcp_ip_server]
[V] 2015-04-06T21:48:00.6253196Z: 127.0.0.1 connected, total: 1 clients [Suave.Tcp.tcp_ip_server.job]
[V] 2015-04-06T21:48:00.6323246Z: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcp_ip_server.job] [Suave.Socket.BufferManager]
[V] 2015-04-06T21:48:00.6423316Z: -> processor [Suave.Web.request_loop.loop]
[V] 2015-04-06T21:48:00.6633465Z: reserving buffer: 802816, free count: 98 [Suave.Web.read_till_pattern.loop] [Suave.Socket.BufferManager]
[V] 2015-04-06T21:48:00.7053906Z: freeing buffer: 802816, free count: 99 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-04-06T21:48:00.7364162Z: reserving buffer: 802816, free count: 98 [Suave.Web.read_till_pattern.loop] [Suave.Socket.BufferManager]
[V] 2015-04-06T21:48:00.9904504Z: tcp request processing failed [Suave.Tcp.tcp_ip_server.job] exn:
System.Exception: did not find header, because header_params received None
   at Suave.Utils.Parsing.headerParams(FSharpOption`1 header)
   at Suave.Web.ParsingAndControl.loop@207-31.Invoke(Tuple`2 _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)

**Comment by haf** [comment]
The first error is interesting; because it means Random(seed) has different implementations on mono vs .Net

**Comment by haf** [comment]
So it turns out RFC1867 that I coded against isn't actually implemented by web servers, and all web servers simply repeat the form-name for multiple files. Gaah.

http://stackoverflow.com/questions/16976299/how-to-create-an-html-form-to-send-http-message-with-multipart-mixed-mime-type/29487399#29487399

**Comment by haf** [comment]
http://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean/28380690#28380690 is another QA about this

**Comment by haf** [comment]
Wow, what a yak.

At least now there are passing integration tests =). Ok, please review again.

**Comment by haf** [comment]
This is the actual input to the web server:

```
POST /filenames HTTP/1.1
Content-Type: multipart/form-data; boundary=b'-sJqodFMqzXPtnZ/hQjmsriBISel
Content-Length: 431
Expect: 100-continue
Connection: keep-alive
Host: localhost:1234

--b'-sJqodFMqzXPtnZ/hQjmsriBISel
Content-Disposition: form-data; name="submit-name"

Larry
--b'-sJqodFMqzXPtnZ/hQjmsriBISel
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--b'-sJqodFMqzXPtnZ/hQjmsriBISel
Content-Disposition: form-data; name="files"; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--b'-sJqodFMqzXPtnZ/hQjmsriBISel--
```

Seems to work.

**Comment by haf** [comment]
AppVeyor is still not happy. Could someone with Windows check out why it can't find the path?

**Comment by relentless** [comment]
Sorry, at work - I think it might just be that it's looking in the release folder for the exe but the build outputs to the debug folder.  Looks like Travis has the same problem, but doesn't consider it a build failure(!).

**Comment by haf** [comment]
No worries, I'm pretty self-sustained with albacore :) I published Http.fs-prerelease to nuget if you wanna give it a ride. I'll delete once this PR and renames etc come together.

**Comment by relentless** [comment]
## Build problem

The reason the unit tests aren't working is just that it's looking in the wrong folder, if you go into build.fsx and change "Run Unit Tests" to this, it will work:

```
ProcessHelper.directExec (fun procInfo ->
    procInfo.FileName <- Path.Combine(unitTestsDir |> outputFolder, "HttpClient.UnitTests.exe")
) |> ignore
```

However, I'm still getting 2 unit test failures and an error in the integration tests.  Unit tests look like the same as before:

## Unit Test failures

formatting different sorts of body/ordinary multipart/form-data: Failed:
should have correct body
Expected: "--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="submit-name"

Larry
--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--mACKqCcIID-J''_PL:hfbFiOLC/cew--
"
Actual: "--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="submit-name"

Larry
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa--

"
  g:\prg\Fuchu\Fuchu\Assertions.fs(13,1): <StartupCode$Fuchu>.$Assertions.Equal@13.Invoke(String msg)
 (00:00:00.0302749)

formatting different sorts of body/multipart/form-data with multipart/mixed: Failed:
should have correct body
Expected: "--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Disposition: form-data; name="submit-name"

Larry
--mACKqCcIID-J''_PL:hfbFiOLC/cew
Content-Type: multipart/mixed; boundary=iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: form-data; name="files"

--iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: file; filename="file1.txt"
Content-Type: text/plain

Hello World
--iDnsCZhfTqMSYsj:LhBTftNfVog:eA
Content-Disposition: file; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--iDnsCZhfTqMSYsj:LhBTftNfVog:eA--
--mACKqCcIID-J''_PL:hfbFiOLC/cew--"
Actual: "--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Disposition: form-data; name="submit-name"

Larry
--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa
Content-Type: multipart/mixed; boundary=BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: form-data; name="files"

--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: file; filename="file1.txt"
Content-Type: text/plain

Hello World
--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF
Content-Disposition: file; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--BgOE:fCUQGnYfKwGMnxoyfwVMbRzZF--

--nLWsTCFurKCiU_PjC/cCmmU-tnJHHa--

"
  g:\prg\Fuchu\Fuchu\Assertions.fs(13,1): <StartupCode$Fuchu>.$Assertions.Equal@13.Invoke(String msg)

## Integration test error

1) Test Error : HttpClient_IntegrationTests+Integration tests.if a response character encoding is NOT specified, and character encoding is NOT specified in the response's content-type header, the body is read using ISO Latin 1 character encoding
   System.ArgumentException : '' is not a supported encoding name.
Parameter name: name
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at HttpClient_IntegrationTests.Integration tests.
if a response character encoding is NOT specified, and character encoding is NOT specified in the response's content-type header, the body is read using ISO Latin 1 character encoding() in
 C:\Programming\FSharp\HTTP\Http.fs\HttpClient.IntegrationTests\HttpClient_IntegrationTests.fs:line 294

**Comment by relentless** [comment]
The integration test is broken because the fix added with this commit has been removed:
https://github.com/relentless/Http.fs/commit/4b535d41aa4cd31a33c02b49a4ac1ca0a8561042

Specifically, readBody should contain

```
match encoding with
    | None -> 
        match response.CharacterSet with
        | null | "" -> Encoding.GetEncoding(ISO_Latin_1)
```

**Comment by relentless** [comment]
But yes, it looks like the implementation of Random is different between Mono and MS .Net.  http://answers.unity3d.com/questions/393825/systemrandom-with-seed-not-matching-net-or-mono.html

**Comment by haf** [comment]
Ok, I hope these three commits have it covered.

Perhaps @forki can tell us how the return value of the process is used to fail the build?

**Comment by forki** [comment]
you mean like https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/OctoTools.fs#L176?

**Comment by haf** [comment]
Yes, exactly =). Is `|>(+)<|` the hug-operator, btw?

**Comment by relentless** [comment]
Yay, working builds!

I think the non-ailing build issue is related to exceptions rather than return values, in that the exception from the missing executable is being swallowed or not raised on Mono.

**Comment by relentless** [comment]
In the middle of moving house, won't have Internet at home for a while, will get back on this ASAP

**Comment by haf** [comment]
How is your house-warming going? =)

**Comment by relentless** [comment]
All moved in and Internet-enabled! Just out of the country at the moment, will be back soon though and should be able to start looking at this again. Sorry for the extended delay.

--- Original Message ---

**Comment by haf** [comment]
Now we have integration tests for sending a binary file, too that are passing with the latest Suave.

**Comment by haf** [comment]
Latest suave https://twitter.com/SuaveIO/status/601018318280126464 -- works on my machine =)

**Comment by haf** [comment]
I have updated the namespaces here, too.

**Comment by haf** [comment]
So on Windows, on AppVeyor, something is obviously deadlocking / locking the async and that never returns. Since the web server runs to completion, sending all its data, I'm a bit surprised. Any insights?

**Comment by haf** [comment]
Some feedback now that all issues have been solved would be great!

**Comment by relentless** [comment]
Good work, nice green builds!  I'm due a 'learning day' at work, so I'll take that soon and try to go through all you've done.  (Although there's a lot to go through!)

**Comment by haf** [comment]
Request for merge!

**Comment by relentless** [comment]
OK, have merged.  Still want to check a few things, and want to go through it before making a NuGet.

**Comment by haf** [comment]
Yes, you should -- I absolutely want feedback and to reach consensus. How about we create issues for each discussion point, and you can cc @haf?

**Pull request merged**
