### PR TITLE
Misc cleanups

### LINKED ISSUE #42: Don't commit packages/
screen shot 2015-01-02 at 20 12 20

zzzzz

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by rodrigovidal** [comment]
@haf I think it would be better if you could split these changes in multiple PRs. This way it would become easier to review. What you think?

**Comment by relentless** [comment]
Agreed.  I appreciate all the work you're doing, but aside from the fact that it's generally good form to have separate PRs for different issues, this turns it into an all-or-nothing proposition and I'm still not convinced about all of the changes you suggest.  I realise it's difficult to separate everything out when you're making a lot of changes, but you can't assume I'm going to include everything.

Also, the PR can't be merged for some reason - will try and check the conflicts tomorrow.  I don't mind merging all of this as one given the amount of change, as long as you accept that I might back out some of the changes.

**Comment by haf** [comment]
Thanks. You can cherry-pick what you want, or you can merge to a branch, check how well it merges, reverse what you don't want and change what is relevant. I've done extremely small commits so that they diff and reverse easily.

**Comment by haf** [comment]
Btw; my main focus is having all-green all the time, and having a build that works on mono, is fast to push/pull, when I work in a repo; that's the underlying reason for this PR. This PR fixes the build when you're not on Windows, which I'm not. I can't easily split it up, since the above 'invariants' of my workflow doesn't hold then -- and I'm really _just interested in getting the API for sending files and multipart forms working_; not primarily in cleaning everything up.

**Comment by Muhomorik** [comment]
NuGet packages are messed up. That is probably why AppVeyor fails. Studio shows 304 errors in solution.
Think it wants packages.config back.

**Comment by haf** [comment]
Can you make it so that I can see the log from appveyor?

An alternative is to simply run build.bat or similar, which will restore, which is what I can send in the PR as soon as I can see the AppVeyor log; normally it's visible when you click the red X in the PR -- is it configured properly?

**Comment by relentless** [comment]
It looks like AppVeyor isn't running a build because the changes don't auto-merge

**Comment by Muhomorik** [comment]
C:\code\fake\src\app\FakeLib\ProcessHelper.fs?

---

## Build Time Report

Target                   Duration

---

Clean                    00:00:00.0052417
BuildClient              00:00:03.1071630
BuildUnitTests           00:00:01.4060098
BuildIntegrationTests    00:00:01.6190793
BuildSampleApplication   00:00:01.2413251
Total:                   00:00:07.4903228

## Status:                  Failure

  1) System.Exception: Start of process ./HttpClient.UnitTests/bin/Release\HttpC
lient.UnitTests.exe failed. Det går inte att hitta filen
   vid Fake.ProcessHelper.directExec@218.Invoke(String message) i C:\code\fake\s
rc\app\FakeLib\ProcessHelper.fs:rad 218
   vid Fake.ProcessHelper.directExec(FSharpFunc`2 configProcessStartInfoF) i C:\
code\fake\src\app\FakeLib\ProcessHelper.fs:rad 213
   vid FSI_0001.Build.clo@51-2.Invoke(Unit _arg2) i D:\Inbox downloads\Http.fs-f
eature-bodies\build.fsx:rad 54
   vid Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) i C:\code\fake
\src\app\FakeLib\TargetHelper.fs:rad 411

**Comment by haf** [comment]
Try without `./`. Btw, that means in Swedish; 'cannot find the file'.

**Comment by relentless** [comment]
I just merged these locally and pushed.  There were a couple of issues with tools, but it build OK locally now.  Will see how it goes down with CI shortly.

**Pull request merged**
