### PR TITLE
Timeout property.

### PR DESCRIPTION
**Pull request by Muhomorik**
Integration test.
- SlowResponse @ Server, do nothing for 10s.
  Unit test
- Test if Timeout is set.

I've decided to go with .Net style and naming. Also, WebException is thrown on timeout, that's how httpWebRequest manages timeouts. Alternative is to return WebExceptionStatus code.
See
https://msdn.microsoft.com/en-us/library/system.net.webexceptionstatus%28v=vs.110%29.aspx

### CODE REVIEW

**Comment by relentless** [comment]
Good work, thanks. I'm still wondering whether we can make it more obvious what unit the timeout is using - I might see how it looks with a unit of measure or calling the function 'withTimeoutMS' before I release it as a nuget.

**Comment by Muhomorik** [comment]
@relentless I don't, honestly, know. MS doesn't have it. 
And during compile, the units of measure are eliminated, so the units are lost at run time.

**Comment by relentless** [comment]
I added a unit of measure, so you call it like withTimeout 100<ms>.  I realise it's just a compile-time thing, but I think it's a good way to specify the units.  The only downside is that if someone already has an <ms>unit of measure defined, one will override the other.  But there doesn't seem to be a standard set of measures now the power pack has been split up, so hopefully that's not much of an issue.

What with the previous changes breaking the API, I'll need to release the next version as 2.x on NuGet, but I want to make sure we include any other breaking changes at the same time, so it might be a little while before this change makes it onto NuGet.

**Comment by relentless** [comment]
The integration tests doesn't work in Mono for some reason (see build: https://travis-ci.org/relentless/Http.fs/builds/57349017).

I've Ignored the test for now, will try and investigate later.

**Pull request merged**
